#!/bin/bash
#By Nexolight

VENDOR=$1
DEVICE=$2
VENDORDIR=$3
PFILES=$4
MK_VENDOR_BLOBS=$VENDORDIR/$DEVICE-vendor.mk
COPYRIGHT=$(cat <<'EOF'
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF
)


echo "Generating makefile for vendor blobs"

(cat << EOF) > $MK_VENDOR_BLOBS
$COPYRIGHT
PRODUCT_COPY_FILES := \\
EOF

COUNT=0
VBLOBS=$(grep -v -E "(^\s*?#.*$)|(^\s*$)" $PFILES)
LINES=$(grep -v -E "(^\s*?#.*$)|(^\s*$)" $PFILES | wc -l | cut -f1)
for VBLOB in $VBLOBS;do
	COUNT=$((COUNT+1))
	if [ $COUNT == $LINES ];then
		echo "	$VENDORDIR/proprietary/$VBLOB:system/$VBLOB" >> $MK_VENDOR_BLOBS	
	else
		echo "	$VENDORDIR/proprietary/$VBLOB:system/$VBLOB \\" >> $MK_VENDOR_BLOBS	
	fi
done

echo "$(call inherit-product-if-exists, $VENDORDIR/$DEVICE-vendor-blobs.mk)" >> $MK_VENDOR_BLOBS

echo "Done"
